"""Public quiz API facade.

Implementation lives in focused modules:

- ``quiz_core``: schemas, constants, and normalization
- ``quiz_importers``: LMS and Canvas importers
- ``quiz_prompts``: prompt and context builders
- ``quiz_generation``: generated quiz and distractor logic
"""

from __future__ import annotations

from .quiz_core import (
    BaseQuizItem,
    CANVAS_FLAG_RE,
    CANVAS_QUESTION_HEADER_RE,
    CHOICE_QUESTION_TYPES,
    ChoiceQuizItem,
    EssayQuizItem,
    EXTERNAL_MIXED_QUIZ_VERSION,
    EXTERNAL_QUIZ_VERSION,
    GENERATED_OPTION_LABELS,
    LABEL_ANSWER_RE,
    MatchingQuizItem,
    OPTION_LABELS,
    POSITION_HEADER_RE,
    QUESTION_TYPES,
    QUIZ_VERSION,
    QuizItemModel,
    TRUE_FALSE_OPTIONS,
    compact_question_with_options,
    is_true_false_options,
    limit_option_text,
    load_quiz,
    normalize_options,
    normalize_question_type,
    normalize_quiz,
    normalize_quiz_item,
    parse_source_pages,
    _normalize_int,
    _normalize_int_list,
    _normalize_option,
    _normalize_points,
    _normalize_string_list,
    _validate_typed_quiz_item,
)
from .quiz_generation import (
    QuizGenerationDiagnostics,
    QuizSourceRecord,
    build_quiz_item,
    generate_quiz,
    load_topic_names_by_chunk,
    _filter_ambiguous_broad_terms,
)
from .quiz_importers import import_canvas_quiz, import_lms_mc_quiz
from .quiz_prompts import (
    DEFAULT_CHOICE_PROMPT,
    DEFAULT_ESSAY_PROMPT,
    DEFAULT_MC_PROMPT,
    build_choice_prompt,
    build_choice_question_guidance,
    build_essay_prompt,
    build_mc_context,
    build_mc_prompt,
    recommended_choice_from_guidance,
)

__all__ = [
    "BaseQuizItem",
    "CANVAS_FLAG_RE",
    "CANVAS_QUESTION_HEADER_RE",
    "CHOICE_QUESTION_TYPES",
    "ChoiceQuizItem",
    "DEFAULT_CHOICE_PROMPT",
    "DEFAULT_ESSAY_PROMPT",
    "DEFAULT_MC_PROMPT",
    "EXTERNAL_MIXED_QUIZ_VERSION",
    "EXTERNAL_QUIZ_VERSION",
    "EssayQuizItem",
    "GENERATED_OPTION_LABELS",
    "LABEL_ANSWER_RE",
    "MatchingQuizItem",
    "OPTION_LABELS",
    "POSITION_HEADER_RE",
    "QUESTION_TYPES",
    "QUIZ_VERSION",
    "QuizGenerationDiagnostics",
    "QuizItemModel",
    "QuizSourceRecord",
    "TRUE_FALSE_OPTIONS",
    "build_choice_prompt",
    "build_choice_question_guidance",
    "build_essay_prompt",
    "build_mc_context",
    "build_mc_prompt",
    "build_quiz_item",
    "compact_question_with_options",
    "generate_quiz",
    "import_canvas_quiz",
    "import_lms_mc_quiz",
    "is_true_false_options",
    "limit_option_text",
    "load_quiz",
    "load_topic_names_by_chunk",
    "normalize_options",
    "normalize_question_type",
    "normalize_quiz",
    "normalize_quiz_item",
    "parse_source_pages",
    "recommended_choice_from_guidance",
    "_filter_ambiguous_broad_terms",
    "_normalize_int",
    "_normalize_int_list",
    "_normalize_option",
    "_normalize_points",
    "_normalize_string_list",
    "_validate_typed_quiz_item",
]
