#!/usr/bin/env python3
"""Register the Ethnos native messaging host with Firefox.

Firefox will only start a native host that is named in a manifest under the
user's own Mozilla directory, and only for the extension IDs that manifest
lists. Installing is therefore two small files and nothing else: no service,
no port, no daemon.

Every target is resolved and printed before anything is written, and uninstall
removes only the exact paths it created.

    python3 deploy/firefox/install_native_host.py            # show what it would do
    python3 deploy/firefox/install_native_host.py --write
    python3 deploy/firefox/install_native_host.py --uninstall --write
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

HOST_NAME = "ethnos_hawkes"
EXTENSION_ID = "ethnos-hawkes@local"

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_HOME = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
INSTALL_DIR = DATA_HOME / "ethnos-hawkes"
LAUNCHER = INSTALL_DIR / "ethnos-hawkes-host"
MANIFEST_DIR = Path.home() / ".mozilla" / "native-messaging-hosts"
MANIFEST = MANIFEST_DIR / f"{HOST_NAME}.json"
LENGTH_PREFIX = struct.Struct("=I")

LAUNCHER_TEMPLATE = """\
#!/bin/sh
# Started by Firefox for the Ethnos Hawkes add-on. Speaks native messaging on
# stdio and exits when Firefox closes the pipe. Generated by
# deploy/firefox/install_native_host.py -- edit that, not this.
exec {python} -m ethnos.hawkes_host
"""


def interpreter() -> Path:
    """Prefer the project venv, so the host has the pipeline's dependencies."""
    venv = PROJECT_ROOT / ".venv" / "bin" / "python"
    return venv if venv.is_file() else Path(sys.executable)


def manifest_body() -> dict:
    return {
        "name": HOST_NAME,
        "description": "Ethnos local solver for the Hawkes add-on",
        "path": str(LAUNCHER),
        "type": "stdio",
        "allowed_extensions": [EXTENSION_ID],
    }


def _atomic_write(path: Path, content: str, mode: int) -> None:
    """Replace one installed file atomically with its final permissions."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        try:
            Path(temporary).unlink()
        except FileNotFoundError:
            pass


def _python_can_start_host(python: Path) -> tuple[bool, str]:
    probe = subprocess.run(
        [str(python), "-c", "import ethnos.hawkes_host"],
        cwd=PROJECT_ROOT,
        text=True,
        capture_output=True,
        timeout=20,
        check=False,
    )
    detail = (probe.stderr or probe.stdout).strip()
    return probe.returncode == 0, detail


def install(write: bool) -> int:
    python = interpreter()
    print(f"interpreter : {python}")
    print(f"launcher    : {LAUNCHER}")
    print(f"manifest    : {MANIFEST}")
    print(f"extension   : {EXTENSION_ID}")
    if not write:
        print("\nnothing written; re-run with --write")
        return 0

    ready, detail = _python_can_start_host(python)
    if not ready:
        print(
            "\nrefusing to install: the selected interpreter cannot import "
            f"ethnos.hawkes_host{': ' + detail if detail else ''}",
            file=sys.stderr,
        )
        print("run `uv sync`, then retry", file=sys.stderr)
        return 1

    _atomic_write(
        LAUNCHER,
        LAUNCHER_TEMPLATE.format(python=shlex.quote(str(python))),
        0o755,
    )
    _atomic_write(MANIFEST, json.dumps(manifest_body(), indent=2) + "\n", 0o644)
    print("\nwrote both files atomically; restart Firefox to pick up the manifest")
    return 0


def uninstall(write: bool) -> int:
    # Only ever these two exact paths, and never a directory.
    targets = [path for path in (MANIFEST, LAUNCHER) if path.is_file()]
    for path in (MANIFEST, LAUNCHER):
        print(f"{'remove' if path in targets else 'absent'}: {path}")
    if not write:
        print("\nnothing removed; re-run with --write")
        return 0
    for path in targets:
        path.unlink()
    try:
        INSTALL_DIR.rmdir()
    except OSError:
        pass  # absent or contains something not owned by this installer
    print("\nremoved; the add-on can no longer reach Ethnos")
    return 0


def check() -> int:
    """Validate installed files and complete a native health round trip."""
    problems: list[str] = []
    if not LAUNCHER.is_file() or not os.access(LAUNCHER, os.X_OK):
        problems.append(f"launcher is missing or not executable: {LAUNCHER}")
    try:
        actual = json.loads(MANIFEST.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        problems.append(f"manifest is unreadable: {exc}")
    else:
        if actual != manifest_body():
            problems.append("manifest content does not match this checkout")
    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 1

    request = json.dumps(
        {
            "protocol_version": 1,
            "operation": "health",
            "request_id": "installer-check",
        }
    ).encode("utf-8")
    try:
        process = subprocess.run(
            [str(LAUNCHER)],
            input=LENGTH_PREFIX.pack(len(request)) + request,
            capture_output=True,
            timeout=20,
            check=False,
        )
        if len(process.stdout) < LENGTH_PREFIX.size:
            raise ValueError(
                process.stderr.decode(errors="replace") or "no native reply"
            )
        (length,) = LENGTH_PREFIX.unpack(process.stdout[: LENGTH_PREFIX.size])
        reply = json.loads(
            process.stdout[LENGTH_PREFIX.size : LENGTH_PREFIX.size + length]
        )
        if process.returncode != 0 or reply.get("status") != "ok":
            raise ValueError(f"unexpected health reply: {reply}")
    except (
        OSError,
        subprocess.TimeoutExpired,
        ValueError,
        json.JSONDecodeError,
    ) as exc:
        print(f"error: native host health check failed: {exc}", file=sys.stderr)
        return 1
    print(f"ok: {LAUNCHER}")
    print(f"ok: {MANIFEST}")
    print("ok: native messaging health round trip")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--write", action="store_true", help="actually change the filesystem"
    )
    parser.add_argument(
        "--uninstall", action="store_true", help="remove what was installed"
    )
    parser.add_argument(
        "--check", action="store_true", help="verify the installed host"
    )
    args = parser.parse_args()
    if args.check:
        if args.uninstall or args.write:
            parser.error("--check cannot be combined with --write or --uninstall")
        return check()
    return uninstall(args.write) if args.uninstall else install(args.write)


if __name__ == "__main__":
    raise SystemExit(main())
